spring:
  datasource:
    url: jdbc:mysql://localhost:3306/BookMyTicket
    drvierClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Electronic1702!
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
 
eureka:
  instance:
      preferIpAddress: true
  client:
    register-with-client: true
    fetch-registry: true
    service-url: 
      defaultZone: http://localhost:8761/eureka/

