spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/BookMyTicket
    drvierClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
 
 eureka:
  client:
    register-with-client: true
    fetch-registry: true
    service-url: 
      defaultZone: http://localhost:8761/eureka/
  instance:
      hostName: localhost
