spring:
  datasource:
    url: jdbc:mysql://bookmyticketdbinstance.ccurtbvhvqj1.ap-south-1.rds.amazonaws.com/BookMyTicket
    drvierClassName: com.mysql.cj.jdbc.Driver
    username: admin
    password: Password1234!
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
 
eureka:
  client:
    register-with-client: true
    fetch-registry: true
    service-url: 
      defaultZone: http://localhost:8761/eureka/
  instance:
      hostName: localhost
