spring:
  datasource:
    url: jdbc:mysql://bookmyticketdbinstance.ccurtbvhvqj1.ap-south-1.rds.amazonaws.com/BookMyTicket
    drvierClassName: com.mysql.cj.jdbc.Driver
    username: admin
    password: Password1234!
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
